### ISSUE TITLE
SsoApi.getCharacterInfo() exception

### ISSUE THREAD

**Issue by GoldenGnu** [burberius/eve-esi#15]
```
javax.ws.rs.ProcessingException: Error refreshing an access token. Response status: 500.
    at org.glassfish.jersey.client.oauth2.AuthCodeGrantImpl.refreshAccessToken(AuthCodeGrantImpl.java:355)
    at net.troja.eve.esi.auth.OAuth.refreshToken(OAuth.java:78)
    at net.troja.eve.esi.auth.OAuth.applyToParams(OAuth.java:35)
    at net.troja.eve.esi.ApiClient.updateParamsForAuth(ApiClient.java:824)
    at net.troja.eve.esi.ApiClient.invokeAPI(ApiClient.java:706)
    at net.troja.eve.esi.api.SsoApi.getCharacterInfo(SsoApi.java:54)
```
SsoApi.getCharacterInfo() throws an exception that is not an ApiException. That is not expected behavior.

**Comment by GoldenGnu** [comment]
https://github.com/burberius/eve-esi/pull/16 fixes this issue, but, needs to be reviewed
